version: '3'
services:
  db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: order_mysql
      MYSQL_USER: order-user
      MYSQL_PASSWORD: tam12345678
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3307:3306" # <host-port>:<container-port>
  zookeeper:
    image:  zookeeper:3.6.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka-order
    depends_on:
      - zookeeper
    ports:
      - "9093:9092" # host : container-port
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic1:1:1"
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    networks:
      - order-network
    restart: always
networks:
  order-network: