# Comment
FROM ubuntu:20.04
ARG current_time=5h18am
RUN echo 'Bay gio la?: $current_time'
CMD ["CMD may gio?: $current_time"]
ENV my_name="John Doe"
RUN echo 'Hello bro $my_name'
CMD ["Hello cmd $my_name"]


