server.port : 8081
spring.security.oauth2:
    resourceserver:
        jwt:
            jwk-set-uri: http://localhost:8080/realms/storm-micro/protocol/openid-connect/certs
    client:
        registration:
            keycloak:
                client-id: storm-gateway
                client-secret: IjadjPFHPt6358jRBiB94dddk1WNKM1e
                authorization-grant-type: authorization_code
                scope: openid
                client-name: storm-gateway
        provider:
            keycloak:
                issuer-uri: http://localhost:8080/realms/storm-micro

spring:
    datasource:
        username: 'root'
        password: 'root123'
        url: jdbc:mysql://localhost:3306/users_trading
        driver-class-name=com:
            mysql:
                cj:
                    jdbc:
                        Driver: com.mysql.cj.jdbc.Driver